menu:
  首页: /
  归档: /archives
  订阅: /atom.xml
  Github: https://github.com/leeluolee
  关于我(简历): /resume

widgets:
- search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  pinterest: true

fancybox: true

google_analytics: UA-41582683-1
rss:
